config/urls.py
from allauth.account.views import LoginView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from apps.core import views as core_views

handler404 = core_views.Error404View.as_view()
handler500 = core_views.Error500View.as_view()
handler403 = core_views.Error403View.as_view()

urlpatterns = [
    path("admin/", admin.site.urls),
    path("authentication/", include("allauth.urls")),
    path("", LoginView.as_view(), name="account_login"),
]

urlpatterns += [
    path("core/", include("apps.core.urls")),
    path("users/", include("apps.users.urls")),
    path("dashboard/", include("apps.dashboard.urls")),
    path("customers/", include("apps.customers.urls")),
    path("authentication/", include("apps.authentication.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    from debug_toolbar.toolbar import debug_toolbar_urls  # noqa

    urlpatterns += debug_toolbar_urls()

    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
    ]

apps/customers/models.py
from allauth.account.models import EmailAddress
from django.db import models
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _
from model_utils.models import SoftDeletableModel, TimeStampedModel

from apps.users.models import User


class Account(SoftDeletableModel, TimeStampedModel):
    user = models.OneToOneField(
        User,
        verbose_name=_("User"),
        on_delete=models.CASCADE,
        related_name="account",
    )

    class Meta:
        verbose_name = _("Account")
        verbose_name_plural = _("Accounts")
        ordering = ("user__last_name", "user__first_name")

    def __str__(self):
        return self.user.get_full_name()

    @cached_property
    def full_name(self):
        return self.user.get_full_name()

    @cached_property
    def is_email_verified(self):
        return EmailAddress.objects.filter(
            user=self.user, verified=True
        ).exists()

apps/templates/includes/alerts.html
<script>
    {% if messages %}
        {% for message in messages %}
            Swal.fire({
                icon: '{{ message.tags }}',
                title: '{{ message.tags|capfirst }}',
                text: '{{ message }}',
                timer: 3500,
                showConfirmButton: false,
                position: 'top-end',
                toast: true,
                timerProgressBar: true,
                customClass: {
                    popup: 'colored-toast',
                    title: 'swal2-title-custom',
                    content: 'swal2-content-custom'
                },
                didOpen: (toast) => {
                    toast.addEventListener('mouseenter', Swal.stopTimer)
                    toast.addEventListener('mouseleave', Swal.resumeTimer)
                }
            });
        {% endfor %}
    {% endif %}

    {% if errors %}
        let modals = [];
        {% for form_name, form_errors in errors.items %}
            {% for field, error_list in form_errors.items %}
                {% for error in error_list %}
                    modals.push({
                        icon: 'error',
                        title: '{{ field }}',
                        text: '{{ error }}',
                        timer: 3500,
                        showConfirmButton: false,
                        position: 'top-end',
                        toast: true,
                        timerProgressBar: true,
                        customClass: {
                            popup: 'colored-toast',
                            title: 'swal2-title-custom',
                            content: 'swal2-content-custom'
                        },
                        didOpen: (toast) => {
                            toast.addEventListener('mouseenter', Swal.stopTimer)
                            toast.addEventListener('mouseleave', Swal.resumeTimer)
                        }
                    })
                {% endfor %}
            {% endfor %}
        {% endfor %}
        if(modals.length > 0){
            modals.forEach(function(element){
                Swal.fire(element)
            })
        }
    {% endif %}

    {% if form.errors %}
        {% for error_list in form.errors.values %}
            {% for error in error_list %}
                Swal.fire({
                    icon: 'error',
                    title: 'Error',
                    text: '{{ error }}',
                    timer: 3500,
                    showConfirmButton: false,
                    position: 'top-end',
                    toast: true,
                    timerProgressBar: true,
                    customClass: {
                        popup: 'colored-toast',
                        title: 'swal2-title-custom',
                        content: 'swal2-content-custom'
                    },
                    didOpen: (toast) => {
                        toast.addEventListener('mouseenter', Swal.stopTimer)
                        toast.addEventListener('mouseleave', Swal.resumeTimer)
                    }
                });
            {% endfor %}
        {% endfor %}
    {% endif %}

    function showAlert(title, message, icon='info'){
        Swal.fire({
            icon: icon,
            title: title,
            text: message,
            timer: 3500,
            showConfirmButton: false,
            position: 'top-end',
            toast: true,
            timerProgressBar: true,
            customClass: {
                popup: 'colored-toast',
                title: 'swal2-title-custom',
                content: 'swal2-content-custom'
            },
            didOpen: (toast) => {
                toast.addEventListener('mouseenter', Swal.stopTimer)
                toast.addEventListener('mouseleave', Swal.resumeTimer)
            }
        });
    }

</script>

apps/templates/includes/aside.html
{% load static %}
{% load i18n %}
{% load humanize %}

<nav id="kt_aside" class="aside aside-default aside-hoverable" data-kt-drawer="true" data-kt-drawer-name="aside" data-kt-drawer-activate="{default: true, lg: false}" data-kt-drawer-overlay="true" data-kt-drawer-width="{default:'200px', '300px': '250px'}" data-kt-drawer-direction="start" data-kt-drawer-toggle="#kt_aside_toggle">
  <div class="aside-logo flex-column-auto px-10 pt-9 pb-5" id="kt_aside_logo">
    <a href="{% url "apps.dashboard:index" %}">
      <img alt="Logo" src="{% static 'assets/images/logos/logo.png' %}" class="max-h-50px logo-default " height="30" />
    </a>
  </div>
  <div class="aside-menu flex-column-fluid ps-3 pe-1">
    <div class="menu menu-sub-indention menu-column menu-rounded menu-title-gray-600 menu-icon-gray-500 menu-active-bg menu-state-primary menu-arrow-gray-500 fw-semibold fs-6 my-5 mt-lg-2 mb-lg-0" id="kt_aside_menu" data-kt-menu="true">
      <div class="hover-scroll-y mx-4" id="kt_aside_menu_wrapper" data-kt-scroll="true" data-kt-scroll-activate="{default: false, lg: true}" data-kt-scroll-height="auto" data-kt-scroll-wrappers="#kt_aside_menu" data-kt-scroll-offset="20px" data-kt-scroll-dependencies="#kt_aside_logo, #kt_aside_footer">
        <div class="menu-item pt-5">
          <div class="menu-content">
            <span class="fw-bold text-muted text-uppercase fs-7">
              Dashboard
            </span>
          </div>
        </div>
        <div class="menu-item">
          {% if perms.customers.view_account %}
            <a class="menu-link {% if "accounts" in request.path %}active{% endif %}" href="{% url 'apps.customers:account_list' %}">
              <span class="menu-icon">
                <i class="ki-duotone ki-people fs-2 me-2">
                  <span class="path1"></span>
                  <span class="path2"></span>
                  <span class="path3"></span>
                  <span class="path4"></span>
                  <span class="path5"></span>
                </i>
              </span>
              <span class="menu-title">
                {% trans 'Accounts' %}
              </span>
            </a>
          {% endif %}
          {% if perms.customers.view_patient %}
            <a class="menu-link {% if "patients" in request.path %}active{% endif %}" href="{% url 'apps.customers:patient_list' %}">
              <span class="menu-icon">
                <i class="fa-solid fa-hospital-user"></i>
              </span>
              <span class="menu-title">
                {% trans 'Patients' %}
              </span>
            </a>
          {% endif %}
          {% if perms.laboratory.view_medicaltest %}
            <a class="menu-link {% if "medical_tests" in request.path %}active{% endif %}" href="{% url 'apps.laboratory:medical_test_list' %}">
              <span class="menu-icon">
                <i class="fa-solid fa-flask"></i>
              </span>
              <span class="menu-title">
                {% trans 'Medical Tests' %}
              </span>
            </a>
          {% endif %}
          {% if perms.laboratory.view_panel %}
            <a class="menu-link {% if "panels" in request.path %}active{% endif %}" href="{% url 'apps.laboratory:panel_list' %}">
              <span class="menu-icon">
                <i class="fa-solid fa-flask-vial"></i>
              </span>
              <span class="menu-title">
                {% trans 'Panels' %}
              </span>
            </a>
          {% endif %}
          {% if perms.laboratory.view_order %}
            <a class="menu-link {% if "/orders/" in request.path %}active{% endif %}" href="{% url 'apps.laboratory:order_list' %}">
              <span class="menu-icon">
                <i class="fa-solid fa-notes-medical"></i>
              </span>
              <span class="menu-title">
                {% trans 'Orders' %}
              </span>
            </a>
          {% endif %}
          {% if perms.laboratory.view_orderresult %}
            <a class="menu-link {% if "results" in request.path %}active{% endif %}" href="{% url 'apps.laboratory:order_result_list' %}">
              <span class="menu-icon">
                <i class="fa-solid fa-briefcase-medical"></i>
              </span>
              <span class="menu-title">
                {% trans 'Results' %}
              </span>
            </a>
          {% endif %}
          {% if perms.laboratory.view_directorder %}
            <a class="menu-link {% if "/direct-orders/" in request.path %}active{% endif %}" href="{% url 'apps.laboratory:direct_order_list' %}">
              <span class="menu-icon">
                <i class="ki-duotone ki-delivery-3                        ">
                  <span class="path1"></span>
                  <span class="path2"></span>
                  <span class="path3"></span>
                </i>
              </span>
              <span class="menu-title">
                {% trans 'Direct Orders' %}
              </span>
            </a>
          {% endif %}
          {% if perms.laboratory.report_order %}
            <a class="menu-link {% if "/orders/export/" in request.path %}active{% endif %}" href="{% url 'apps.reports:order_export' %}">
              <span class="menu-icon">
                <i class="ki-duotone ki-cheque">
                  <span class="path1"></span>
                  <span class="path2"></span>
                  <span class="path3"></span>
                  <span class="path4"></span>
                  <span class="path5"></span>
                  <span class="path6"></span>
                  <span class="path7"></span>
                </i>
              </span>
              <span class="menu-title">
                {% trans 'Reports' %}
              </span>
            </a>
          {% endif %}
        </div>
        <div class="menu-item">
          <div class="menu-content">
            <div class="separator mx-1 my-4"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="aside-footer flex-column-auto pb-5 d-none" id="kt_aside_footer">
    <a href="index.html" class="btn btn-light-primary w-100">Button</a>
  </div>
</nav>

apps/templates/includes/breadcrumb.html
<ul class="breadcrumb fw-semibold fs-base my-1">
    {% for crumb in breadcrumbs %}
        {% if not forloop.last %}
            <li class="breadcrumb-item text-muted">
                <a href="{{ crumb.url }}" class="text-muted text-hover-primary">
                    {{ crumb.title }}
                </a>
            </li>
        {% else %}
            <li class="breadcrumb-item text-dark">{{ crumb.title }}</li>
        {% endif %}
    {% endfor %}
</ul>

apps/templates/includes/footer.html
{% load i18n %}

<footer class="footer py-4 d-flex flex-lg-column" id="kt_footer">
  <div class="container-fluid d-flex flex-column flex-md-row flex-stack">
    <div class="text-gray-900 order-2 order-md-1">
      <span class="text-muted fw-semibold me-2">2024&copy;</span>
      <a href="#" target="_blank" class="text-gray-800 text-hover-primary">
        Knowing Labs Lis
      </a>
    </div>
    <ul class="menu menu-gray-600 menu-hover-primary fw-semibold order-1">
      <li class="menu-item">
        <a href="https://knowinglabs.com/pages/collection-instructions" target="_blank" class="menu-link px-2">
          {% trans "Collection Instructions" %}
        </a>
      </li>
      <li class="menu-item">
        <a href="https://knowinglabs.com/pages/faqs" target="_blank" class="menu-link px-2">
          {% trans "FAQS" %}
        </a>
      </li>
      <li class="menu-item">
        <a href="https://knowinglabs.com/policies/terms-of-service" target="_blank" class="menu-link px-2">
          {% trans "Terms of service" %}
        </a>
      </li>
    </ul>
  </div>
</footer>

apps/templates/includes/pagination.html
{% load i18n %}
{% load pagination %}

<div class="row">
    <div class="col-sm-12 col-md-5 d-flex align-items-center justify-content-center justify-content-md-start">
        <div id="kt_accounts_table_length" class="dataTables_length">
            <label>
                <select name="items_per_page" aria-controls="kt_accounts_table" class="form-select form-select-sm" id="itemsPerPageSelect">
                    <option value="6" {% if paginator.per_page == 6 %}selected{% endif %}>5</option>
                    <option value="10" {% if paginator.per_page == 10 %}selected{% endif %}>10</option>
                    <option value="25" {% if paginator.per_page == 25 %}selected{% endif %}>25</option>
                    <option value="50" {% if paginator.per_page == 50 %}selected{% endif %}>50</option>
                </select>
            </label>
        </div>
    </div>

    <div class="col-sm-12 col-md-7 d-flex align-items-center justify-content-center justify-content-md-end">
        {% if is_paginated %}
        <div id="kt_accounts_table_paginate" class="dataTables_paginate paging_simple_numbers">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li id="kt_accounts_table_previous" class="page-item previous">
                        <a href="{% param_replace page=page_obj.previous_page_number %}" class="page-link">
                            <i class="previous"></i>
                        </a>
                    </li>
                {% else %}
                    <li id="kt_accounts_table_previous" class="page-item previous disabled">
                        <a href="#" class="page-link">
                            <i class="previous"></i>
                        </a>
                    </li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <li class="page-item active">
                            <a href="#" class="page-link">{{ num }}</a>
                        </li>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                        <li class="page-item">
                            <a href="{% param_replace page=num %}" class="page-link">{{ num }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li id="kt_accounts_table_next" class="page-item next">
                        <a href="{% param_replace page=page_obj.next_page_number %}" class="page-link">
                            <i class="next"></i>
                        </a>
                    </li>
                {% else %}
                    <li id="kt_accounts_table_next" class="page-item next disabled">
                        <a href="#" class="page-link">
                            <i class="next"></i>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
        {% endif %}
    </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
      const itemsPerPageSelect = document.getElementById('itemsPerPageSelect');
      if (itemsPerPageSelect) {
          itemsPerPageSelect.addEventListener('change', function() {
              const selectedValue = this.value;
              const currentUrl = new URL(window.location.href);
              currentUrl.searchParams.set('items_per_page', selectedValue);
              currentUrl.searchParams.delete('page');
              window.location.href = currentUrl.toString();
          });
      }
  });
</script>

apps/templates/includes/scripts_css.html
{% load static %}

<link href="{% static 'assets/plugins/custom/leaflet/leaflet.bundle.css' %}" rel="stylesheet"></link>
<link href="{% static 'assets/plugins/custom/datatables/datatables.bundle.css' %}" rel="stylesheet"></link>
<link href="{% static 'assets/plugins/global/plugins.bundle.css' %}" rel="stylesheet"></link>
<link href="{% static 'assets/css/style.bundle.css' %}" rel="stylesheet"></link>

apps/templates/includes/scripts_js.html
{% load static %}

<script src="{% static 'assets/plugins/global/plugins.bundle.js' %}"></script>
<script src="{% static 'assets/plugins/custom/leaflet/leaflet.bundle.js' %}"></script>
<script src="{% static 'assets/plugins/custom/datatables/datatables.bundle.js' %}"></script>
<script src="{% static 'assets/js/scripts.bundle.js' %}"></script>
<script src="{% static 'assets/js/widgets.bundle.js' %}"></script>
<script src="{% static 'assets/js/custom/widgets.js' %}"></script>
<script src="{% static 'assets/js/custom/apps/chat/chat.js' %}"></script>
<script src="{% static 'assets/js/custom/authentication/sign-in/general.js' %}"></script>